<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="1"
            tests="3">

  <testsuite name="createUserTest"
    errors="0" failures="1" hostname="" id="" package="createUserTest" skipped="1"
    tests="3" time="10.29" timestamp="Sun, 12 Nov 2017 02:24:58 GMT">
  
    <testcase name="login" classname="createUserTest" time="5.974" assertions="1">

    
    </testcase>
  
    <testcase name="create-user" classname="createUserTest" time="4.312" assertions="1">  <failure message="Testing if the URL equals &quot;https://192.168.56.102/index.php?menu=userlist&quot;.">    at Object.create-user (/home/juan/public_html/issabel-e2e/tests/createUserTest.js:25:15)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)</failure>

    
    </testcase>
  

  

  
    
    <testcase
      name="check-if-user-exists" classname="createUserTest">
      <skipped />
    </testcase>
    
  
  </testsuite>
</testsuites>
